/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2022-06-26
Author:   Kasianenko Mykyta Mihailovich CS-25
******************************************************************************
*/

#include <stdio.h>
#include "stm32f4xx.h"
#include "stm32f4xx_rcc.h"
#include "stm32f4xx_gpio.h"

void Delay(uint32_t nCount) {
    while (nCount--) {}
}

// світлодіоди
GPIO_InitTypeDef get_gpio_led_config() {
    GPIO_InitTypeDef gpioConf;
    gpioConf.GPIO_Pin = GPIO_Pin_12 | GPIO_Pin_13 | GPIO_Pin_14 | GPIO_Pin_15;
    gpioConf.GPIO_Mode = GPIO_Mode_OUT;
    gpioConf.GPIO_Speed = GPIO_Speed_100MHz;
    gpioConf.GPIO_OType = GPIO_OType_PP;
    gpioConf.GPIO_PuPd = GPIO_PuPd_NOPULL;
    return gpioConf;
}

// кнопка
GPIO_InitTypeDef get_gpio_button_config() {
    GPIO_InitTypeDef gpioConf;
    gpioConf.GPIO_Pin = GPIO_Pin_0; // пін це кнопка
    gpioConf.GPIO_Mode = GPIO_Mode_IN;
    return gpioConf;
}

int main(void) {
    int next_led_id = 4;

    GPIO_InitTypeDef gpioConf;

    gpioConf = get_gpio_button_config();
    RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);
    GPIO_Init(GPIOA, &gpioConf);

    gpioConf = get_gpio_led_config();
    RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOD, ENABLE);
    GPIO_Init(GPIOD, &gpioConf);

    while (1) {
        if (GPIO_ReadInputDataBit(GPIOA, GPIO_Pin_0) == 0) {
            if (4 == next_led_id) {
                GPIO_SetBits(GPIOD, GPIO_Pin_15);
                Delay(50000);
                GPIO_ResetBits(GPIOD, GPIO_Pin_15);
                next_led_id = 3;
            } else if (3 == next_led_id) {
                GPIO_SetBits(GPIOD, GPIO_Pin_14);
                Delay(50000);
                GPIO_ResetBits(GPIOD, GPIO_Pin_14);
                next_led_id = 1;
            } else if (1 == next_led_id) {
                GPIO_SetBits(GPIOD, GPIO_Pin_13);
                Delay(50000);
                GPIO_ResetBits(GPIOD, GPIO_Pin_13);
                next_led_id = 2;
            } else if (2 == next_led_id) {
                GPIO_SetBits(GPIOD, GPIO_Pin_12);
                Delay(50000);
                GPIO_ResetBits(GPIOD, GPIO_Pin_12);
                next_led_id = 4;
            }
            Delay(5000);
            while (GPIO_ReadInputDataBit(GPIOA, GPIO_Pin_0) == 0);
            Delay(5000);
        }
    }
}